export { default as TeeStamp } from './TeeStamp'
export { default as FairwayLineStamp } from './FairwayLineStamp'
export { default as FairwayFlowerStamp } from './FairwayFlowerStamp'
export { default as FairwayDriveStamp } from './FairwayDriveStamp'
export { default as FairwayElbow60Stamp } from './FairwayElbow60Stamp'
export { default as GreenStamp } from './GreenStamp'
export { default as BunkerStamp } from './BunkerStamp'
export { default as WaterStamp } from './WaterStamp'
export type { StampProps } from './stampTypes'
